FROM elasticsearch:5.6.10-alpine

MAINTAINER Valentin Boyanov <valentin@onestic.com>

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu